secretflow/kuscia

- scripts/deploy/start_standalone.sh
support install kuscia with out root permission
> fix install kuscia without root permission

- Makefile
- scripts/deploy/create_token.sh
- scripts/test/integration_test.sh
I have read the CLA Document and I hereby sign the CLA
> Fix: fix integration_test.sh for bash 3.x

- cmd/kuscia/autonomy/autonomy.go
- cmd/kuscia/master/master.go
- docs/reference/api_whitelist_config_cn.md
- etc/kuscia.yaml
- pkg/gateway/clusters/master.go
- pkg/gateway/config/inner_config.go
- pkg/utils/kusciaconfig/service_config.go
- scripts/deploy/start_autonomy.sh
- scripts/deploy/start_lite.sh
feat: K3S Master API Whitelists
> feat: K3S Master API Whitelists

- .circleci/config.yml
自动化推送镜像到阿里云仓库，分支为master且打新标签时触发执行
> Circlecitest

- pkg/kusciaapi/handler/httphandler/job/watch.go
- scripts/deploy/start_secretpad.sh
- scripts/deploy/start_standalone.sh
1 fix watch feature
2 copy secretpad certs
> fix watch feature

- .circleci/config.yml
- .circleci/deps-config.yml
> circleci 修复

- docs/deployment/K8s_deployment_kuscia/K8s_master_lite_cn.md
修复K8s_master_lite_cn.md文档中命令拼写错误
> fix: misspelling

- pkg/datamesh/dataserver/io/builtin/dataio.go
> repo-sync-2024-09-10T19:41:20+0800

- changelog/v0.12.0_CHANGELOG.md
- changelog/v0.13.0_CHANGELOG.md
1. Add 0.13.0 change logs docs
2. Add 0.12.0 change logs docs
> changelog: add v0.13.0 and 0.12.0 release changelogs

- docs/deployment/Docker_deployment_kuscia/deploy_dataproxy_cn.md
fixed : https://github.com/secretflow/kuscia/issues/558
> 根据kuscia的issues/558进行文档的修改

- docs/deployment/logdescription.md
- docs/locales/en/LC_MESSAGES/deployment/kuscia_ports_cn.po
- docs/locales/en/LC_MESSAGES/deployment/logdescription.po
> 【OSCP】【文档季】【KUSCIA】文档「日志说明」翻译成英文文档

- docs/locales/en/LC_MESSAGES/deployment/kuscia_ports_cn.po
> 【OSCP】【文档季】【KUSCIA】文档「Kuscia 端口介绍」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/concepts/domaindatagrant_cn.po
> 【OSCP】【文档季】【KUSCIA】文档「DomainDataGrant」翻译成英文文档

- docs/locales/en/LC_MESSAGES/troubleshoot/concept/kuscia_vs_ray.po
- docs/locales/en/LC_MESSAGES/troubleshoot/deployment/wsl_start_docker.po
> 【文档季】【KUSCIA】文档「使用 WSL 注意事项]、[Kuscia 与 Ray 的区别」翻译成英文文档

- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/mysql_derived_merge.po
I have read the CLA Document and I hereby sign the CLA
> 【文档季】【KUSCIA】文档「MySQL（数据库） optimizer_switch 参数优化]、[Log」翻译成英文文档 #594

- docs/locales/en/LC_MESSAGES/reference/overview.po
Translate overview.po documentation to English
Complete English translation of all msgid entries in the reference/overview.md 
documentation. This includes translation of technical concepts related to 
privacy-preserving computation, deployment scenarios, and Kuscia architecture 
details.
Documentation-URL: ../../reference/overview.md
> 【OSCP】【KUSCIA】文档「概述」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/architecture_cn.po
Document English translation of architecture reference，Fixed #538
> 【OSCP】【KUSCIA】文档「架构」翻译成英文文档

- docs/deployment/K8s_deployment_kuscia/K8s_p2p_cn.md
- scripts/user/create_example_job.sh
fixed #560 
job列表：
任务运行截图：
job详情：
任务结果：
> 【OSCP】【文档季】【KUSCIA】验证文档「部署点对点集群」，包括验证文档流程以及示例代码的正确性

- docs/locales/en/LC_MESSAGES/reference/apis/summary_cn.po
- docs/reference/apis/summary_cn.md
Type of change
Description:
1. Translate `summary_cn.md` in English
2. Adjust the format in Chinese version document
3. Resolves https://github.com/secretflow/kuscia/issues/549
> Docs: translate `summary_cn.md` in English

- docs/locales/en/LC_MESSAGES/reference/concepts/kusciatask_cn.po
> 【OSCP】【KUSCIA】文档「KusciaTask」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/concepts/appimage_cn.po
> 【OSCP】【KUSCIA】文档「AppImage」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/concepts/kusciajob_cn.po
> 【OSCP】【KUSCIA】文档「KusciaJob」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/appimage_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/docker_cpp_copy.po
- docs/reference/apis/appimage_cn.md
> 【OSCP】【KUSCIA】文档「Docker 24.0 环境中 C++17 文件复制权限问题]、[AppImage」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/datamesh/domaindatasource_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/kusciaapi_store_endpoint.po
- docs/reference/apis/datamesh/domaindatasource_cn.md
> 【OSCP】【KUSCIA】文档「OSS（对象存储服务）Endpoint 配置问题]、[DomainDataSource」翻译成英文文档

- docs/deployment/K8s_deployment_kuscia/K8s_master_lite_cn.md
- docs/deployment/K8s_deployment_kuscia/K8s_p2p_cn.md
- docs/deployment/K8s_deployment_kuscia/deploy_with_runp_cn.md
- docs/deployment/K8s_deployment_kuscia/k8s_deploy_kuscia_with_rootless.md
- docs/locales/en/LC_MESSAGES/deployment/K8s_deployment_kuscia/K8s_master_lite_cn.po
- docs/locales/en/LC_MESSAGES/deployment/K8s_deployment_kuscia/K8s_p2p_cn.po
- docs/locales/en/LC_MESSAGES/deployment/K8s_deployment_kuscia/deploy_with_runp_cn.po
- docs/locales/en/LC_MESSAGES/deployment/K8s_deployment_kuscia/index.po
- docs/locales/en/LC_MESSAGES/deployment/K8s_deployment_kuscia/k8s_deploy_kuscia_with_rootless.po
- docs/locales/en/LC_MESSAGES/deployment/operation_cn.po
> 【OSCP】【KUSCIA】文档「K8s 集群部署 Kuscia]、[运维操作」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/domain_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/deployment/FATE_deploy_failed.po
- docs/reference/apis/domain_cn.md
> [oscp]文档【KUSCIA】文档「FATE 部署失败]、[Domain」翻译成英文文档 #584

- docs/locales/en/LC_MESSAGES/reference/apis/error_code_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/docker_memory_limit.po
> 【OSCP】【KUSCIA】文档「如何通过 Docker 命令对已部署的节点进行 Memory 扩容]、[Error Code」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/kusciajob_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/runtask/FATE_run_job_failed.po
- docs/reference/apis/kusciajob_cn.md
- docs/troubleshoot/runtask/FATE_run_job_failed.md
> 【OSCP】 【KUSCIA】文档「FATE 作业运行失败]、[KusciaJob」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/concepts/interopconfig_cn.po
> 【OSCP】【KUSCIA】文档「InteropConfig」翻译成英文文档

- .gitignore
- docs/locales/en/LC_MESSAGES/reference/apis/health_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/k8s_ulimit_check.po
- docs/reference/apis/health_cn.md
> 【文档季】【KUSCIA】文档「Kuscia K8s 部署模式下 SecretFlow 应用线程限制问题]、[Health」翻译成英文文档 #595

- docs/locales/en/LC_MESSAGES/troubleshoot/deployment/create_fsnotify_failed.po
- docs/locales/en/LC_MESSAGES/troubleshoot/network/network_authorization_check.po
> 【OSCP】【KUSCIA】文档「Kuscia 启动失败：Create fsnotify failed]、[授权错误排查」翻译成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/datamesh/domaindata_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/change_pod_mtu.po
- docs/reference/apis/datamesh/domaindata_cn.md
> 【OSCP】【KUSCIA】文档「MTU 配置导致的网络异常]、[DomainData」翻译成英文文档

- docs/getting_started/quickstart_cn.md
> fix:shell error in the doc of the chinese version kuscia

- docs/locales/en/LC_MESSAGES/deployment/Docker_deployment_kuscia/deploy_upgrade_kuscia_cn.po
> 【OSCP】【KUSCIA】翻译文档「升级 Kuscia 版本」成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/domaindata_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/deployment/kuscia_mysql_kine.po
- docs/reference/apis/domaindata_cn.md
> 【OSCP】【KUSCIA】文档「Kine 表问题导致 Kuscia 启动失败]、[DomainData」翻译成英文文档

- docs/locales/en/LC_MESSAGES/deployment/Docker_deployment_kuscia/docker_deploy_kuscia_with_rootless.po
> 【OSCP】【KUSCIA】翻译文档「非 root 用户部署节点」成英文文档

- docs/locales/en/LC_MESSAGES/tutorial/user_defined_service_route.po
- docs/tutorial/user_defined_service_route.md
> 【KUSCIA】翻译文档「如何给 Kuscia 自定义 Service 路由」成英文文档

- docs/reference/concepts/domaindata_cn.md
fix: docs check domaindata url 404
> fix: docs check domaindata

- docs/deployment/Docker_deployment_kuscia/deploy_p2p_cn.md
- docs/locales/en/LC_MESSAGES/deployment/Docker_deployment_kuscia/deploy_p2p_cn.po
> 【OSCP】【KUSCIA】翻译文档「多机部署点对点集群」成英文文档

- docs/locales/en/LC_MESSAGES/reference/apis/config_cn.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/mysql_derived_merge.po
- docs/locales/en/LC_MESSAGES/troubleshoot/parameter_tuning/mysql_too_many_connections.po
- docs/reference/apis/config_cn.md
> 【文档季】【KUSCIA】文档「数据库连接数过多]、[Config」翻译成英文文档 #593

- docs/deployment/Docker_deployment_kuscia/deploy_clustered_cn.md
- docs/deployment/Docker_deployment_kuscia/deploy_master_lite_cn.md
- docs/deployment/Docker_deployment_kuscia/deploy_p2p_cn.md
- docs/development/build_kuscia_cn.md
- docs/development/register_custom_image.md
- docs/getting_started/quickstart_cn.md
- docs/tutorial/security_plan_cn.md
Fixed #522 
- 将$KUSCIA_IMAGE 替换成 ${KUSCIA_IMAGE}
- 在文档中使用环境变量传递 Token
> 【OSCP】【KUSCIA】修复文档中的一些问题
